package spring_data_jpa.demo.model.dto.request;

import lombok.Getter;
import lombok.Setter;
import spring_data_jpa.demo.model.Product;
import spring_data_jpa.demo.model.response.ProductResponse;

@Setter
@Getter
public class ProductRequest {
    private String productName;
    private int unitPrice;
    private String description;
    public Product toEntity() {
        return new Product(
                null, // ID will be generated by the database
                this.productName,
                this.unitPrice,
                this.description,
                null
        );
    }
    public Product toEntity(Long id) {
        return new Product(
                id,
                this.productName,
                this.unitPrice,
                this.description,
                null
        );
    }
    public ProductResponse toProduct(Long id){
        return new ProductResponse(
                id,
                this.productName,
                this.unitPrice,
                this.description
        );

    }

}
